# Generated by Django 2.2.8 on 2020-01-30 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('companyId', models.CharField(max_length=32, verbose_name='公司id')),
                ('companyShortName', models.CharField(max_length=100, verbose_name='公司简称')),
                ('companyFullName', models.CharField(max_length=100, verbose_name='公司全称')),
                ('companyLogo', models.ImageField(max_length=255, upload_to='', verbose_name='公司Logo')),
                ('companySize', models.SmallIntegerField(choices=[(0, '15-50'), (1, '50-150'), (2, '150-500'), (3, '500-2000'), (4, '2000以上')], verbose_name='公司规模')),
                ('industryField', models.CharField(max_length=100, verbose_name='经营领域')),
                ('financeStage', models.BooleanField(choices=[(0, '需要'), (1, '不需要')], verbose_name='是否需要融资')),
                ('companyLabelList', models.CharField(help_text='多个标签之间用逗号分隔', max_length=200, verbose_name='公司标签')),
                ('businessLicense', models.ImageField(blank=True, null=True, upload_to='license', verbose_name='营业执照')),
                ('capital', models.IntegerField(help_text='单位：万', verbose_name='注册资金')),
                ('createPerson', models.CharField(max_length=32, verbose_name='创始人')),
                ('createPersonIntro', models.TextField(verbose_name='创始人简介')),
                ('companyIntro', models.TextField(verbose_name='公司介绍')),
                ('legalRepresentative', models.CharField(blank=True, max_length=32, null=True, verbose_name='法人代表')),
                ('legalize', models.BooleanField(choices=[(0, '未认证'), (1, '已认证')], default=0, verbose_name='是否经过认证')),
                ('latitude', models.CharField(max_length=32, verbose_name='纬度')),
                ('longitude', models.CharField(max_length=32, verbose_name='经度')),
            ],
            options={
                'verbose_name': '公司列表',
                'verbose_name_plural': '公司列表',
            },
        ),
        migrations.CreateModel(
            name='JobBigCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
            ],
            options={
                'verbose_name': '职位主分类',
                'verbose_name_plural': '职位主分类',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('positionName', models.CharField(max_length=200, verbose_name='职位名称')),
                ('companyId', models.CharField(max_length=32, verbose_name='所属公司')),
                ('firstType', models.CharField(help_text='多个分类之间用逗号分隔，例：销售类', max_length=100, verbose_name='第一分类')),
                ('secondType', models.CharField(help_text='多个分类之间用逗号分隔，例：销售管理', max_length=100, verbose_name='第二分类')),
                ('thirdType', models.CharField(help_text='多个分类之间用逗号分隔，例：大客户销售管理', max_length=100, verbose_name='第三分类')),
                ('skillLabels', models.CharField(help_text='多个分类之间用逗号分隔', max_length=100, verbose_name='技术标签')),
                ('positionLabels', models.CharField(help_text='多个分类之间用逗号分隔', max_length=100, verbose_name='职位标签')),
                ('industryLabels', models.CharField(help_text='多个分类之间用逗号分隔', max_length=100, verbose_name='行业标签')),
                ('positionIntro', models.TextField(verbose_name='职位描述')),
                ('city', models.CharField(max_length=32, verbose_name='工作地点')),
                ('district', models.CharField(blank=True, max_length=32, null=True, verbose_name='工作地点-区')),
                ('salary', models.CharField(help_text='例：10k-20k', max_length=32, verbose_name='月薪')),
                ('workYear', models.CharField(help_text='例：5-10', max_length=32, verbose_name='工作时间')),
                ('jobNature', models.SmallIntegerField(choices=[(0, '兼职'), (1, '全职')], help_text='兼职/全职', verbose_name='工作类型')),
                ('education', models.SmallIntegerField(choices=[(0, '小学'), (1, '初中'), (2, '高中'), (3, '专科'), (4, '本科'), (5, '硕士'), (6, '博士')], verbose_name='学历')),
                ('isSchoolJob', models.BooleanField(verbose_name='是否为校招')),
                ('positionAdvantage', models.CharField(blank=True, help_text='多个之间用逗号分隔', max_length=200, null=True, verbose_name='职位优势')),
                ('subwayLine', models.CharField(blank=True, help_text='例：1号线', max_length=100, null=True, verbose_name='地铁')),
                ('stationName', models.CharField(blank=True, help_text='例：西单站', max_length=32, null=True, verbose_name='站名')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pub_position', to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '职位列表',
                'verbose_name_plural': '职位列表',
            },
        ),
        migrations.CreateModel(
            name='JobSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='home.JobBigCategory', verbose_name='所属主分类')),
            ],
            options={
                'verbose_name': '职位子分类',
                'verbose_name_plural': '职位子分类',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.IntegerField(verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='home.JobSubCategory', verbose_name='所属子分类')),
            ],
            options={
                'verbose_name': '职位分类',
                'verbose_name_plural': '职位分类',
            },
        ),
    ]
