# Generated by Django 2.2.8 on 2020-01-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='financeStage',
            field=models.CharField(max_length=32, verbose_name='是否需要融资'),
        ),
    ]
