# Generated by Django 2.2.8 on 2020-01-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200131_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='companyLogo',
            field=models.ImageField(upload_to='companyLogo', verbose_name='公司Logo'),
        ),
    ]
