# Generated by Django 2.2.8 on 2020-01-22 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category_jobbigcategory_jobsubcategory_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='home.JobSubCategory', verbose_name='所属子分类'),
        ),
        migrations.AlterField(
            model_name='jobsubcategory',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='home.JobBigCategory', verbose_name='所属主分类'),
        ),
    ]
