# Generated by Django 2.2.8 on 2020-02-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_company_createtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='signature',
            field=models.CharField(default='撒大空间上的卡就是你的卡是男的看见啊手机上的那款难得看见阿撒', max_length=40, verbose_name='公司签名'),
            preserve_default=False,
        ),
    ]
