# Generated by Django 2.2.8 on 2020-02-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_company_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='legalRepresentative',
            field=models.CharField(max_length=32, verbose_name='法人代表'),
        ),
    ]
