# Generated by Django 2.2.8 on 2020-03-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='companyEmail',
            field=models.TextField(default='12345@aa.com', verbose_name='企业邮箱列表'),
            preserve_default=False,
        ),
    ]
