# Generated by Django 2.2.8 on 2020-03-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_company_companyemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='positionIntroHtml',
            field=models.TextField(default='<h1>hello</h1>', verbose_name='职位描述（html）'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='positionIntro',
            field=models.TextField(verbose_name='职位描述（md）'),
        ),
    ]
