# Generated by Django 2.2.8 on 2019-12-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_type',
            field=models.BooleanField(choices=[(0, '普通用户'), (1, '企业用户')], default=1, verbose_name='用户类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='work_status',
            field=models.SmallIntegerField(blank=True, choices=[(0, '已离职'), (1, '在职中'), (2, '保密'), (3, '已退休')], default=1, null=True, verbose_name='工作状态'),
        ),
    ]
