# Generated by Django 2.2.8 on 2019-12-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191222_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='名称')),
                ('order', models.SmallIntegerField(verbose_name='序号')),
                ('status', models.BooleanField(choices=[(0, '上线'), (1, '下线')])),
            ],
        ),
    ]
