# Generated by Django 2.2.8 on 2019-12-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_province'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': '省份', 'verbose_name_plural': '省份'},
        ),
    ]
