# Generated by Django 2.2.8 on 2020-03-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200303_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[(0, '女'), (1, '男')], max_length=1, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='account',
            name='unifiedAdmission',
            field=models.CharField(blank=True, choices=[(1, '统招'), (0, '非统招')], max_length=1, null=True, verbose_name='是否统招'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[(0, '求职者'), (1, '招人者')], default=0, max_length=1, verbose_name='用户类型'),
        ),
        migrations.AlterField(
            model_name='account',
            name='work_status',
            field=models.CharField(blank=True, choices=[(0, '已离职'), (1, '在职中'), (2, '保密'), (3, '已退休')], default=1, max_length=1, null=True, verbose_name='工作状态'),
        ),
    ]
