# Generated by Django 2.2.8 on 2019-12-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191223_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.BooleanField(choices=[(0, '普通用户'), (1, '企业用户')], default=0, verbose_name='用户类型'),
        ),
        migrations.AlterField(
            model_name='province',
            name='status',
            field=models.BooleanField(choices=[(0, True), (1, False)], verbose_name='是否上线'),
        ),
    ]
