# Generated by Django 2.2.8 on 2019-12-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191224_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, default='media/avatar/avatar.jpg', null=True, upload_to='avatar', verbose_name='头像'),
        ),
    ]
