# Generated by Django 2.2.8 on 2020-03-05 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200303_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('0', '女'), ('1', '男')], max_length=1, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='account',
            name='unifiedAdmission',
            field=models.CharField(blank=True, choices=[('1', '统招'), ('0', '非统招')], max_length=1, null=True, verbose_name='是否统招'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('0', '求职者'), ('1', '招人者')], default=0, max_length=1, verbose_name='用户类型'),
        ),
        migrations.AlterField(
            model_name='account',
            name='work_status',
            field=models.CharField(blank=True, choices=[('0', '已离职'), ('1', '在职中'), ('2', '保密'), ('3', '已退休')], default=1, max_length=1, null=True, verbose_name='工作状态'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='发布日期')),
                ('is_delete', models.BooleanField(choices=[(1, '是'), (0, '否')], default=0, verbose_name='是否删除')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
            options={
                'verbose_name': '动态',
                'verbose_name_plural': '动态',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.News', verbose_name='动态id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
        ),
    ]
