# Generated by Django 2.2.8 on 2020-01-22 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191227_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='jobsubcategory',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='JobBigCategory',
        ),
        migrations.DeleteModel(
            name='JobSubCategory',
        ),
    ]
