# Generated by Django 2.2.8 on 2020-03-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200306_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='html_code',
            field=models.TextField(default='asdasd', verbose_name='html内容'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='md_code',
            field=models.TextField(default='asdasd', verbose_name='markdown内容'),
            preserve_default=False,
        ),
    ]
