# Generated by Django 2.2.8 on 2020-03-07 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200306_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_num',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.TextField(default='asdasd', verbose_name='文章标签'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='asda', max_length=100, verbose_name='文章标题'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='update_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='更新日期'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(auto_now=True, verbose_name='发布日期'),
        ),
    ]
