# Generated by Django 2.2.8 on 2020-03-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200307_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新日期'),
        ),
    ]
