# Generated by Django 2.2.8 on 2020-03-08 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200307_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='简历标题')),
                ('html_code', models.TextField(verbose_name='html内容')),
                ('md_code', models.TextField(verbose_name='markdown内容')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='发布日期')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='更新日期')),
                ('is_delete', models.BooleanField(choices=[(1, '是'), (0, '否')], default=0, verbose_name='是否删除')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
            options={
                'verbose_name': '简历',
                'verbose_name_plural': '简历',
            },
        ),
    ]
