# Generated by Django 2.2.8 on 2020-03-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_show',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=1, verbose_name='是否展示'),
        ),
    ]
