# Generated by Django 2.2.8 on 2020-03-10 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_resume_is_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Article', verbose_name='文章')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_parent', to='user.ArticleComments', verbose_name='父级评论')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply', to='user.ArticleComments', verbose_name='被回复评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户')),
            ],
            options={
                'verbose_name': '文章评论',
                'verbose_name_plural': '文章评论',
            },
        ),
    ]
