# Generated by Django 2.2.8 on 2020-03-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_articlecomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomments',
            name='parent',
            field=models.BigIntegerField(default=0, verbose_name='父级评论'),
        ),
        migrations.AlterField(
            model_name='articlecomments',
            name='reply',
            field=models.BigIntegerField(default=0, verbose_name='被回复评论'),
        ),
    ]
