# Generated by Django 2.2.8 on 2020-03-24 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200317_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlelike',
            name='news_id',
        ),
        migrations.RemoveField(
            model_name='newscomments',
            name='article',
        ),
        migrations.AddField(
            model_name='articlelike',
            name='article_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Article', verbose_name='动态id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newscomments',
            name='news',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.News', verbose_name='文章'),
            preserve_default=False,
        ),
    ]
