# Generated by Django 2.2.8 on 2020-03-31 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200328_1451'),
        ('user', '0016_auto_20200324_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(0, '未查看'), (1, '已查看')], verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='投递时间')),
                ('is_delete', models.BooleanField(choices=[(1, '是'), (0, '否')], default=0, verbose_name='是否删除')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Position', verbose_name='职位')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投递人')),
            ],
            options={
                'verbose_name': '简历投递记录',
                'verbose_name_plural': '简历投递记录',
            },
        ),
    ]
