# Generated by Django 2.2.8 on 2020-03-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_deliveryrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrecord',
            name='status',
            field=models.BooleanField(choices=[(0, '未查看'), (1, '已查看')], default=0, verbose_name='状态'),
        ),
    ]
