# Generated by Django 2.2.8 on 2020-04-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20200331_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryrecord',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='isdelivery_delete',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=0, verbose_name='投递者是否删除'),
        ),
        migrations.AddField(
            model_name='deliveryrecord',
            name='isreceiver_delete',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=0, verbose_name='接收者是否删除'),
        ),
    ]
